-- ============================================================
-- 1. Riders
-- First, they do not reference anything other than themselves.
-- ============================================================

CREATE TABLE Riders (
    rider_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rider_name     VARCHAR(100) NOT NULL,
    phone_number   VARCHAR(20)  NOT NULL,
    email          VARCHAR(255) NOT NULL,

    CONSTRAINT pk_riders
        PRIMARY KEY (rider_id),

    CONSTRAINT uq_riders_email
        UNIQUE (email)
);


-- ============================================================
-- 2. Drivers
-- Similarly to Riders, they do not reference anything other than themselves.
-- ============================================================

CREATE TABLE Drivers (
    driver_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    driver_name     VARCHAR(100) NOT NULL,
    phone_number    VARCHAR(20)  NOT NULL,
    license_number  VARCHAR(50)  NOT NULL,

    CONSTRAINT pk_drivers
        PRIMARY KEY (driver_id),

    CONSTRAINT uq_drivers_license_number
        UNIQUE (license_number)
);


-- ============================================================
-- 3. Trips
-- It references both, Drivers and Riders
-- Cannot exist without either of them.
-- ============================================================

CREATE TABLE Trips (
    trip_id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rider_id          INTEGER NOT NULL,
    driver_id         INTEGER NOT NULL,
    fare_amount       NUMERIC(10, 2) NOT NULL,
    trip_date         TIMESTAMP NOT NULL,
    pickup_location   VARCHAR(255) NOT NULL,
    dropoff_location  VARCHAR(255) NOT NULL,

    CONSTRAINT pk_trips
        PRIMARY KEY (trip_id),

    CONSTRAINT chk_trips_fare_amount
        CHECK (fare_amount >= 0),

    CONSTRAINT fk_trips_rider
        FOREIGN KEY (rider_id)
        REFERENCES Riders (rider_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_trips_driver
        FOREIGN KEY (driver_id)
        REFERENCES Drivers (driver_id)
        ON DELETE RESTRICT
);


-- ============================================================
-- 4. Driver Badges
-- Although it does not reference other tables,
-- It comes after Drivers in the schema.
-- ============================================================

CREATE TABLE Driver_Badges (
    badge_id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    badge_name         VARCHAR(100) NOT NULL,
    badge_description  TEXT NOT NULL,

    CONSTRAINT pk_driver_badges
        PRIMARY KEY (badge_id),

    CONSTRAINT uq_driver_badges_name
        UNIQUE (badge_name)
);


-- ============================================================
-- 5. Driver Badge Awards
-- It sits at the end because it references Drivers and Badges.
-- This is the junction table for Drivers and Badges.
-- ============================================================

CREATE TABLE Driver_Badge_Awards (
    driver_id    INTEGER NOT NULL,
    badge_id     INTEGER NOT NULL,
    date_awarded DATE NOT NULL,

    CONSTRAINT pk_driver_badge_awards
        PRIMARY KEY (driver_id, badge_id),

    CONSTRAINT fk_badge_awards_driver
        FOREIGN KEY (driver_id)
        REFERENCES Drivers (driver_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_badge_awards_badge
        FOREIGN KEY (badge_id)
        REFERENCES Driver_Badges (badge_id)
        ON DELETE RESTRICT
);